/** ISO 3166-1 alpha-2 code → flag emoji (regional indicator symbols). */
export function flagEmoji(code: string): string {
  return code.toUpperCase().replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export type Country = { code: string; name: string };

const RAW: [string, string][] = [
  ["FR", "France"],
  ["BE", "Belgique"],
  ["CH", "Suisse"],
  ["LU", "Luxembourg"],
  ["DE", "Allemagne"],
  ["ES", "Espagne"],
  ["IT", "Italie"],
  ["PT", "Portugal"],
  ["GB", "Royaume-Uni"],
  ["IE", "Irlande"],
  ["NL", "Pays-Bas"],
  ["MA", "Maroc"],
  ["DZ", "Algérie"],
  ["TN", "Tunisie"],
  ["SN", "Sénégal"],
  ["CI", "Côte d'Ivoire"],
  ["CM", "Cameroun"],
  ["ML", "Mali"],
  ["CD", "Congo (RDC)"],
  ["CG", "Congo"],
  ["GN", "Guinée"],
  ["BF", "Burkina Faso"],
  ["TG", "Togo"],
  ["BJ", "Bénin"],
  ["GA", "Gabon"],
  ["MG", "Madagascar"],
  ["CV", "Cap-Vert"],
  ["GW", "Guinée-Bissau"],
  ["CF", "République centrafricaine"],
  ["TD", "Tchad"],
  ["NE", "Niger"],
  ["MR", "Mauritanie"],
  ["RW", "Rwanda"],
  ["BI", "Burundi"],
  ["KM", "Comores"],
  ["DJ", "Djibouti"],
  ["EG", "Égypte"],
  ["LY", "Libye"],
  ["NG", "Nigeria"],
  ["GH", "Ghana"],
  ["ZA", "Afrique du Sud"],
  ["KE", "Kenya"],
  ["ET", "Éthiopie"],
  ["AO", "Angola"],
  ["MZ", "Mozambique"],
  ["US", "États-Unis"],
  ["CA", "Canada"],
  ["MX", "Mexique"],
  ["BR", "Brésil"],
  ["AR", "Argentine"],
  ["CL", "Chili"],
  ["CO", "Colombie"],
  ["PE", "Pérou"],
  ["UY", "Uruguay"],
  ["PY", "Paraguay"],
  ["BO", "Bolivie"],
  ["EC", "Équateur"],
  ["VE", "Venezuela"],
  ["CU", "Cuba"],
  ["HT", "Haïti"],
  ["DO", "République dominicaine"],
  ["JM", "Jamaïque"],
  ["TR", "Turquie"],
  ["RU", "Russie"],
  ["UA", "Ukraine"],
  ["PL", "Pologne"],
  ["RO", "Roumanie"],
  ["BG", "Bulgarie"],
  ["GR", "Grèce"],
  ["SE", "Suède"],
  ["NO", "Norvège"],
  ["DK", "Danemark"],
  ["FI", "Finlande"],
  ["IS", "Islande"],
  ["AT", "Autriche"],
  ["CZ", "Tchéquie"],
  ["SK", "Slovaquie"],
  ["HU", "Hongrie"],
  ["HR", "Croatie"],
  ["RS", "Serbie"],
  ["SI", "Slovénie"],
  ["BA", "Bosnie-Herzégovine"],
  ["MK", "Macédoine du Nord"],
  ["AL", "Albanie"],
  ["ME", "Monténégro"],
  ["XK", "Kosovo"],
  ["MD", "Moldavie"],
  ["BY", "Biélorussie"],
  ["LT", "Lituanie"],
  ["LV", "Lettonie"],
  ["EE", "Estonie"],
  ["MT", "Malte"],
  ["CY", "Chypre"],
  ["MC", "Monaco"],
  ["AD", "Andorre"],
  ["SM", "Saint-Marin"],
  ["VA", "Vatican"],
  ["LI", "Liechtenstein"],
  ["CN", "Chine"],
  ["JP", "Japon"],
  ["KR", "Corée du Sud"],
  ["KP", "Corée du Nord"],
  ["IN", "Inde"],
  ["PK", "Pakistan"],
  ["BD", "Bangladesh"],
  ["ID", "Indonésie"],
  ["MY", "Malaisie"],
  ["SG", "Singapour"],
  ["TH", "Thaïlande"],
  ["VN", "Vietnam"],
  ["PH", "Philippines"],
  ["MM", "Myanmar"],
  ["KH", "Cambodge"],
  ["LA", "Laos"],
  ["NP", "Népal"],
  ["LK", "Sri Lanka"],
  ["MN", "Mongolie"],
  ["KZ", "Kazakhstan"],
  ["UZ", "Ouzbékistan"],
  ["AF", "Afghanistan"],
  ["IR", "Iran"],
  ["IQ", "Irak"],
  ["SY", "Syrie"],
  ["LB", "Liban"],
  ["JO", "Jordanie"],
  ["IL", "Israël"],
  ["PS", "Palestine"],
  ["SA", "Arabie saoudite"],
  ["AE", "Émirats arabes unis"],
  ["QA", "Qatar"],
  ["KW", "Koweït"],
  ["BH", "Bahreïn"],
  ["OM", "Oman"],
  ["YE", "Yémen"],
  ["GE", "Géorgie"],
  ["AM", "Arménie"],
  ["AZ", "Azerbaïdjan"],
  ["AU", "Australie"],
  ["NZ", "Nouvelle-Zélande"],
  ["FJ", "Fidji"],
] as const;

export const COUNTRIES: Country[] = RAW.map(([code, name]) => ({ code, name })).sort((a, b) =>
  a.name.localeCompare(b.name, "fr"),
);

export function countryLabel(code: string): string {
  const c = COUNTRIES.find((x) => x.code === code);
  return c ? `${flagEmoji(c.code)} ${c.name}` : code;
}
