/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AnnoncesIndexRouteImport } from './routes/annonces.index'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsIdRouteImport } from './routes/clubs.$id'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as JoueursIndexRouteImport } from './routes/joueurs.index'
import { Route as JoueursIdRouteImport } from './routes/joueurs.$id'
import { Route as PreparateursIndexRouteImport } from './routes/preparateurs.index'
import { Route as PreparateursIdRouteImport } from './routes/preparateurs.$id'
import { Route as SeancesIndexRouteImport } from './routes/seances.index'
import { Route as AuthenticatedAnnoncesNouvelleRouteImport } from './routes/_authenticated/annonces.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AnnoncesIndexRoute = AnnoncesIndexRouteImport.update({
  id: '/annonces/',
  path: '/annonces/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/annonces/$id',
  path: '/annonces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIdRoute = ClubsIdRouteImport.update({
  id: '/clubs/$id',
  path: '/clubs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueursIndexRoute = JoueursIndexRouteImport.update({
  id: '/joueurs/',
  path: '/joueurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueursIdRoute = JoueursIdRouteImport.update({
  id: '/joueurs/$id',
  path: '/joueurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparateursIndexRoute = PreparateursIndexRouteImport.update({
  id: '/preparateurs/',
  path: '/preparateurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparateursIdRoute = PreparateursIdRouteImport.update({
  id: '/preparateurs/$id',
  path: '/preparateurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeancesIndexRoute = SeancesIndexRouteImport.update({
  id: '/seances/',
  path: '/seances/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnnoncesNouvelleRoute =
  AuthenticatedAnnoncesNouvelleRouteImport.update({
    id: '/annonces/nouvelle',
    path: '/annonces/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/joueurs/$id': typeof JoueursIdRoute
  '/preparateurs/$id': typeof PreparateursIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/joueurs/': typeof JoueursIndexRoute
  '/preparateurs/': typeof PreparateursIndexRoute
  '/seances/': typeof SeancesIndexRoute
  '/annonces/nouvelle': typeof AuthenticatedAnnoncesNouvelleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/joueurs/$id': typeof JoueursIdRoute
  '/preparateurs/$id': typeof PreparateursIdRoute
  '/annonces': typeof AnnoncesIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/joueurs': typeof JoueursIndexRoute
  '/preparateurs': typeof PreparateursIndexRoute
  '/seances': typeof SeancesIndexRoute
  '/annonces/nouvelle': typeof AuthenticatedAnnoncesNouvelleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/premium': typeof PremiumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/joueurs/$id': typeof JoueursIdRoute
  '/preparateurs/$id': typeof PreparateursIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/joueurs/': typeof JoueursIndexRoute
  '/preparateurs/': typeof PreparateursIndexRoute
  '/seances/': typeof SeancesIndexRoute
  '/_authenticated/annonces/nouvelle': typeof AuthenticatedAnnoncesNouvelleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/premium'
    | '/sitemap.xml'
    | '/admin'
    | '/bibliotheque'
    | '/messages'
    | '/notifications'
    | '/profil'
    | '/tableau-de-bord'
    | '/annonces/$id'
    | '/clubs/$id'
    | '/ebooks/$slug'
    | '/joueurs/$id'
    | '/preparateurs/$id'
    | '/annonces/'
    | '/clubs/'
    | '/ebooks/'
    | '/joueurs/'
    | '/preparateurs/'
    | '/seances/'
    | '/annonces/nouvelle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/premium'
    | '/sitemap.xml'
    | '/admin'
    | '/bibliotheque'
    | '/messages'
    | '/notifications'
    | '/profil'
    | '/tableau-de-bord'
    | '/annonces/$id'
    | '/clubs/$id'
    | '/ebooks/$slug'
    | '/joueurs/$id'
    | '/preparateurs/$id'
    | '/annonces'
    | '/clubs'
    | '/ebooks'
    | '/joueurs'
    | '/preparateurs'
    | '/seances'
    | '/annonces/nouvelle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/premium'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/annonces/$id'
    | '/clubs/$id'
    | '/ebooks/$slug'
    | '/joueurs/$id'
    | '/preparateurs/$id'
    | '/annonces/'
    | '/clubs/'
    | '/ebooks/'
    | '/joueurs/'
    | '/preparateurs/'
    | '/seances/'
    | '/_authenticated/annonces/nouvelle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PremiumRoute: typeof PremiumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnnoncesIdRoute: typeof AnnoncesIdRoute
  ClubsIdRoute: typeof ClubsIdRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  JoueursIdRoute: typeof JoueursIdRoute
  PreparateursIdRoute: typeof PreparateursIdRoute
  AnnoncesIndexRoute: typeof AnnoncesIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
  JoueursIndexRoute: typeof JoueursIndexRoute
  PreparateursIndexRoute: typeof PreparateursIndexRoute
  SeancesIndexRoute: typeof SeancesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/annonces/': {
      id: '/annonces/'
      path: '/annonces'
      fullPath: '/annonces/'
      preLoaderRoute: typeof AnnoncesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/annonces/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$id': {
      id: '/clubs/$id'
      path: '/clubs/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof ClubsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueurs/': {
      id: '/joueurs/'
      path: '/joueurs'
      fullPath: '/joueurs/'
      preLoaderRoute: typeof JoueursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueurs/$id': {
      id: '/joueurs/$id'
      path: '/joueurs/$id'
      fullPath: '/joueurs/$id'
      preLoaderRoute: typeof JoueursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparateurs/': {
      id: '/preparateurs/'
      path: '/preparateurs'
      fullPath: '/preparateurs/'
      preLoaderRoute: typeof PreparateursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparateurs/$id': {
      id: '/preparateurs/$id'
      path: '/preparateurs/$id'
      fullPath: '/preparateurs/$id'
      preLoaderRoute: typeof PreparateursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seances/': {
      id: '/seances/'
      path: '/seances'
      fullPath: '/seances/'
      preLoaderRoute: typeof SeancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/annonces/nouvelle': {
      id: '/_authenticated/annonces/nouvelle'
      path: '/annonces/nouvelle'
      fullPath: '/annonces/nouvelle'
      preLoaderRoute: typeof AuthenticatedAnnoncesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedAnnoncesNouvelleRoute: typeof AuthenticatedAnnoncesNouvelleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedAnnoncesNouvelleRoute: AuthenticatedAnnoncesNouvelleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PremiumRoute: PremiumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnnoncesIdRoute: AnnoncesIdRoute,
  ClubsIdRoute: ClubsIdRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  JoueursIdRoute: JoueursIdRoute,
  PreparateursIdRoute: PreparateursIdRoute,
  AnnoncesIndexRoute: AnnoncesIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  EbooksIndexRoute: EbooksIndexRoute,
  JoueursIndexRoute: JoueursIndexRoute,
  PreparateursIndexRoute: PreparateursIndexRoute,
  SeancesIndexRoute: SeancesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
